# Generated by Django 4.0.4 on 2022-05-23 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task', models.CharField(max_length=100)),
                ('responsible', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=10000)),
                ('task_creation_date', models.DateField()),
                ('wished_due_date', models.DateField()),
                ('estimated_duration', models.CharField(max_length=100)),
                ('active', models.BooleanField(default=1)),
            ],
        ),
    ]
